// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BranchConfig { branches: Array<string> | null, branches_ignore: Array<string> | null, }