// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CommandExecution { command_id: string, exit_code: number | null, stdout: string, stderr: string, duration_ms: bigint, executed_at: string, success: boolean, }