// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ExecuteCommandRequest { command_id: string, timeout_seconds: bigint | null, }