// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecution } from "./CommandExecution";

export interface ExecuteCommandResponse { execution: CommandExecution, }