// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Runner } from "./Runner";
import type { Step } from "./Step";

export interface Job { "runs-on": Runner, steps: Array<Step>, needs: Array<string> | null, environment: string | null, "working-directory": string | null, }