// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowCommand } from "./WorkflowCommand";
import type { WorkflowInfo } from "./WorkflowInfo";

export interface ScanWorkflowsResponse { workflows: Array<WorkflowInfo>, commands: Array<WorkflowCommand>, }