// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Step { id: string | null, name: string | null, uses: string | null, run: string | null, shell: string | null, "working-directory": string | null, env: Record<string, string> | null, }