// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerConfig } from "./TriggerConfig";

export type Trigger = string | Array<string> | TriggerConfig;