// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchConfig } from "./BranchConfig";
import type { CronSchedule } from "./CronSchedule";

export interface TriggerConfig { push: BranchConfig | null, pull_request: BranchConfig | null, schedule: Array<CronSchedule> | null, }