// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Job } from "./Job";
import type { Trigger } from "./Trigger";

export interface Workflow { name: string | null, on: Trigger, jobs: Record<string, Job>, }