// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WorkflowInfo { name: string, file_path: string, jobs_count: number, commands_count: number, }