// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WorkflowCommand { id: string, workflow_name: string, job_name: string, step_name: string | null, command: string, shell: string | null, working_directory: string | null, environment: Record<string, string> | null, file_path: string, }