# rustfmt configuration for nocodo project
# Ensures consistent code formatting across all Rust components

# Use stable features only
edition = "2021"

# Line width and formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
reorder_imports = true
reorder_modules = true

# Miscellaneous
use_small_heuristics = "Default"
chain_width = 60
single_line_if_else_max_width = 50
