# rustfmt configuration for nocodo project
# Ensures consistent code formatting across all Rust components

# Use stable features only
edition = "2021"

# Line width and formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# Function and struct formatting
fn_single_line = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# Control flow formatting
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"
where_single_line = false

# String and array formatting
format_strings = true
format_macro_matchers = true
normalize_comments = true
normalize_doc_attributes = true

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Miscellaneous
use_small_heuristics = "Default"
binop_separator = "Front"
chain_width = 60
single_line_if_else_max_width = 50
