[server]
host = "127.0.0.1"
port = 8082

[database]
path = "/tmp/nocodo-test.db"

[socket]
path = "/tmp/nocodo-manager-test.sock"

# JWT secret for testing
jwt_secret = "test-jwt-secret-for-development-only"