use std::path::Path;

use crate::error::AgentError;

/// Write a Diesel model struct (generated by the LLM) to disk via schema-codegen.
///
/// Returns the relative file path that was written.
pub fn write_diesel_model(project_path: &Path, code: &str) -> Result<String, AgentError> {
    schema_codegen::write_model_file(project_path, code)
        .map_err(|e| AgentError::Other(e.to_string()))
}

/// Append a Diesel `table!` block (generated by the LLM) to schema.rs.
///
/// Returns the relative file path that was written.
pub fn write_diesel_schema(project_path: &Path, code: &str) -> Result<String, AgentError> {
    schema_codegen::append_table_to_schema(project_path, code)
        .map_err(|e| AgentError::Other(e.to_string()))
}

/// Write a praxis spec module to `backend/src/praxis/specs/{module_name}.rs`.
///
/// Overwrites on regeneration. Ensures `praxis/mod.rs` and `praxis/specs/mod.rs`
/// declare the module. Returns the relative file path written.
pub fn write_praxis_spec(
    project_path: &Path,
    module_name: &str,
    code: &str,
) -> Result<String, AgentError> {
    schema_codegen::write_praxis_spec(project_path, module_name, code)
        .map_err(|e| AgentError::Other(e.to_string()))
}
