use std::path::Path;

use crate::error::AgentError;

/// Write a Diesel model struct (generated by the LLM) to disk via schema-codegen.
///
/// Returns the relative file path that was written.
pub fn write_diesel_model(project_path: &Path, code: &str) -> Result<String, AgentError> {
    schema_codegen::write_model_file(project_path, code)
        .map_err(|e| AgentError::Other(e.to_string()))
}

/// Append a Diesel `table!` block (generated by the LLM) to schema.rs.
///
/// Returns the relative file path that was written.
pub fn write_diesel_schema(project_path: &Path, code: &str) -> Result<String, AgentError> {
    schema_codegen::append_table_to_schema(project_path, code)
        .map_err(|e| AgentError::Other(e.to_string()))
}
