//! Deterministic code generator: `SchemaDef` → Rust structs + SQLite DDL.
//!
//! The pipeline is intentionally split into granular stages so callers can
//! inspect or transform the intermediate representation.
//!
//! ```text
//! SchemaDef ──► Vec<TableModel> ──► Rust source code
//!                    │
//!                    └──► SQLite DDL
//! ```

use shared_types::{ColumnDef, DataType, SchemaDef, TableDef};
use std::fmt::Write;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// Intermediate model of a table, decoupled from SchemaDef.
#[derive(Debug, Clone, PartialEq)]
pub struct TableModel {
    /// Original SQL table name (plural snake_case).
    pub sql_name: String,
    /// Rust struct name (singular PascalCase derived from sql_name).
    pub rust_name: String,
    pub columns: Vec<ColumnModel>,
}

/// Intermediate model of a column.
#[derive(Debug, Clone, PartialEq)]
pub struct ColumnModel {
    /// SQL column name (snake_case).
    pub sql_name: String,
    /// Rust field name (snake_case, same as sql_name).
    pub rust_name: String,
    /// Rust type expression (e.g. `String`, `Option<i64>`).
    pub rust_type: String,
    /// SQLite affinity type (TEXT, INTEGER, REAL, NUMERIC, BLOB).
    pub sql_type: String,
    pub nullable: bool,
    pub primary_key: bool,
    pub foreign_key: Option<ForeignKeyModel>,
}

/// Foreign key reference in the intermediate model.
#[derive(Debug, Clone, PartialEq)]
pub struct ForeignKeyModel {
    pub ref_table: String,
    pub ref_column: String,
}

/// Result of running both generators.
#[derive(Debug, Clone, PartialEq)]
pub struct CodegenResult {
    pub rust_code: String,
    pub sql_ddl: String,
}

// ---------------------------------------------------------------------------
// Stage 1: SchemaDef → AST
// ---------------------------------------------------------------------------

/// Convert a `SchemaDef` into a stable, queryable AST (`Vec<TableModel>`).
pub fn parse_schema_def(schema: &SchemaDef) -> Vec<TableModel> {
    schema.tables.iter().map(parse_table_def).collect()
}

fn parse_table_def(table: &TableDef) -> TableModel {
    let sql_name = table.name.clone();
    let rust_name = sql_name_to_rust_struct(&sql_name);
    let columns = table.columns.iter().map(parse_column_def).collect();
    TableModel {
        sql_name,
        rust_name,
        columns,
    }
}

fn parse_column_def(col: &ColumnDef) -> ColumnModel {
    let rust_type = data_type_to_rust(&col.data_type, col.nullable);
    let sql_type = data_type_to_sql(&col.data_type);
    ColumnModel {
        sql_name: col.name.clone(),
        rust_name: col.name.clone(),
        rust_type,
        sql_type: sql_type.to_string(),
        nullable: col.nullable,
        primary_key: col.primary_key,
        foreign_key: col.foreign_key.as_ref().map(|fk| ForeignKeyModel {
            ref_table: fk.ref_table.clone(),
            ref_column: fk.ref_column.clone(),
        }),
    }
}

// ---------------------------------------------------------------------------
// Stage 2a: AST → Rust source code
// ---------------------------------------------------------------------------

/// Generate a single Rust struct from a `TableModel`.
pub fn table_model_to_rust_struct(table: &TableModel) -> String {
    let mut out = String::new();
    writeln!(&mut out, "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]").unwrap();
    writeln!(&mut out, "pub struct {} {{", table.rust_name).unwrap();
    for col in &table.columns {
        writeln!(&mut out, "    pub {}: {},", col.rust_name, col.rust_type).unwrap();
    }
    writeln!(&mut out, "}}").unwrap();
    out
}

/// Generate a Rust module containing all structs plus shared imports.
pub fn tables_to_rust_module(tables: &[TableModel]) -> String {
    let mut out = String::new();
    writeln!(&mut out, "// Generated by schema-codegen").unwrap();
    writeln!(&mut out, "// Do not edit manually").unwrap();
    writeln!(&mut out).unwrap();
    for table in tables {
        out.push_str(&table_model_to_rust_struct(table));
        out.push('\n');
    }
    out
}

// ---------------------------------------------------------------------------
// Stage 2b: AST → SQLite DDL
// ---------------------------------------------------------------------------

/// Generate a `CREATE TABLE` statement for a single `TableModel`.
pub fn table_model_to_sql_create(table: &TableModel) -> String {
    let mut out = String::new();
    writeln!(&mut out, "CREATE TABLE IF NOT EXISTS {} (", table.sql_name).unwrap();

    let col_count = table.columns.len();
    let mut fks: Vec<String> = Vec::new();

    for (i, col) in table.columns.iter().enumerate() {
        let comma = if i < col_count - 1 || !fks.is_empty() { "," } else { "" };
        let mut constraints = String::new();
        if col.primary_key {
            constraints.push_str(" PRIMARY KEY AUTOINCREMENT");
        }
        if !col.nullable && !col.primary_key {
            constraints.push_str(" NOT NULL");
        }
        writeln!(
            &mut out,
            "    {} {}{}{}",
            col.sql_name, col.sql_type, constraints, comma
        )
        .unwrap();

        if let Some(fk) = &col.foreign_key {
            fks.push(format!(
                "    FOREIGN KEY ({}) REFERENCES {}({})",
                col.sql_name, fk.ref_table, fk.ref_column
            ));
        }
    }

    // Append foreign key constraints at the end
    let fk_count = fks.len();
    for (i, fk) in fks.iter().enumerate() {
        let comma = if i < fk_count - 1 { "," } else { "" };
        writeln!(&mut out, "{}{}", fk, comma).unwrap();
    }

    writeln!(&mut out, ");").unwrap();
    out
}

/// Generate a full SQLite DDL script from a slice of `TableModel`s.
pub fn tables_to_sql_ddl(tables: &[TableModel]) -> String {
    let mut out = String::new();
    writeln!(&mut out, "-- Generated by schema-codegen").unwrap();
    writeln!(&mut out, "-- Do not edit manually").unwrap();
    writeln!(&mut out).unwrap();
    for table in tables {
        out.push_str(&table_model_to_sql_create(table));
        out.push('\n');
    }
    out
}

// ---------------------------------------------------------------------------
// Convenience: SchemaDef → both outputs
// ---------------------------------------------------------------------------

/// Run the full pipeline: `SchemaDef` → Rust code + SQL DDL.
pub fn generate(schema: &SchemaDef) -> CodegenResult {
    let tables = parse_schema_def(schema);
    CodegenResult {
        rust_code: tables_to_rust_module(&tables),
        sql_ddl: tables_to_sql_ddl(&tables),
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn data_type_to_rust(dt: &DataType, nullable: bool) -> String {
    let base = match dt {
        DataType::Text => "String",
        DataType::Integer => "i64",
        DataType::Real => "f64",
        DataType::Boolean => "bool",
        DataType::Date => "i64",
        DataType::DateTime => "i64",
    };
    if nullable {
        format!("Option<{}>", base)
    } else {
        base.to_string()
    }
}

fn data_type_to_sql(dt: &DataType) -> &'static str {
    match dt {
        DataType::Text => "TEXT",
        DataType::Integer => "INTEGER",
        DataType::Real => "REAL",
        // SQLite has no native BOOLEAN; store as INTEGER 0/1
        DataType::Boolean => "INTEGER",
        // Store timestamps as Unix epoch seconds
        DataType::Date => "INTEGER",
        DataType::DateTime => "INTEGER",
    }
}

/// Convert a plural snake_case SQL table name to singular PascalCase Rust struct name.
fn sql_name_to_rust_struct(sql_name: &str) -> String {
    let singular = to_singular(sql_name);
    to_pascal_case(&singular)
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let mut word = first.to_uppercase().to_string();
                    word.extend(chars.map(|c| c.to_lowercase().to_string()));
                    word
                }
            }
        })
        .collect()
}

/// Very light singularisation heuristic.
fn to_singular(s: &str) -> String {
    if s.ends_with("ies") {
        format!("{}y", &s[..s.len() - 3])
    } else if s.ends_with("s") && !s.ends_with("ss") && !s.ends_with("us") {
        s[..s.len() - 1].to_string()
    } else {
        s.to_string()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use shared_types::ForeignKeyDef;

    fn sample_schema() -> SchemaDef {
        SchemaDef {
            name: "Test App".to_string(),
            tables: vec![
                TableDef {
                    name: "users".to_string(),
                    columns: vec![
                        ColumnDef {
                            name: "id".to_string(),
                            data_type: DataType::Integer,
                            nullable: false,
                            primary_key: true,
                            foreign_key: None,
                        },
                        ColumnDef {
                            name: "name".to_string(),
                            data_type: DataType::Text,
                            nullable: false,
                            primary_key: false,
                            foreign_key: None,
                        },
                        ColumnDef {
                            name: "email".to_string(),
                            data_type: DataType::Text,
                            nullable: true,
                            primary_key: false,
                            foreign_key: None,
                        },
                        ColumnDef {
                            name: "active".to_string(),
                            data_type: DataType::Boolean,
                            nullable: false,
                            primary_key: false,
                            foreign_key: None,
                        },
                    ],
                },
                TableDef {
                    name: "orders".to_string(),
                    columns: vec![
                        ColumnDef {
                            name: "id".to_string(),
                            data_type: DataType::Integer,
                            nullable: false,
                            primary_key: true,
                            foreign_key: None,
                        },
                        ColumnDef {
                            name: "user_id".to_string(),
                            data_type: DataType::Integer,
                            nullable: false,
                            primary_key: false,
                            foreign_key: Some(ForeignKeyDef {
                                ref_table: "users".to_string(),
                                ref_column: "id".to_string(),
                            }),
                        },
                        ColumnDef {
                            name: "total".to_string(),
                            data_type: DataType::Real,
                            nullable: false,
                            primary_key: false,
                            foreign_key: None,
                        },
                    ],
                },
            ],
        }
    }

    #[test]
    fn test_parse_schema_def() {
        let schema = sample_schema();
        let tables = parse_schema_def(&schema);
        assert_eq!(tables.len(), 2);
        assert_eq!(tables[0].sql_name, "users");
        assert_eq!(tables[0].rust_name, "User");
        assert_eq!(tables[1].sql_name, "orders");
        assert_eq!(tables[1].rust_name, "Order");
    }

    #[test]
    fn test_table_model_to_rust_struct() {
        let schema = sample_schema();
        let tables = parse_schema_def(&schema);
        let rust = table_model_to_rust_struct(&tables[0]);
        assert!(rust.contains("pub struct User"));
        assert!(rust.contains("pub id: i64,"));
        assert!(rust.contains("pub name: String,"));
        assert!(rust.contains("pub email: Option<String>,"));
        assert!(rust.contains("pub active: bool,"));
    }

    #[test]
    fn test_table_model_to_sql_create() {
        let schema = sample_schema();
        let tables = parse_schema_def(&schema);
        let sql = table_model_to_sql_create(&tables[1]);
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS orders"));
        assert!(sql.contains("id INTEGER PRIMARY KEY AUTOINCREMENT"));
        assert!(sql.contains("user_id INTEGER NOT NULL"));
        assert!(sql.contains("total REAL NOT NULL"));
        assert!(sql.contains(
            "FOREIGN KEY (user_id) REFERENCES users(id)"
        ));
    }

    #[test]
    fn test_generate_full() {
        let schema = sample_schema();
        let result = generate(&schema);
        assert!(result.rust_code.contains("pub struct User"));
        assert!(result.rust_code.contains("pub struct Order"));
        assert!(result.sql_ddl.contains("CREATE TABLE IF NOT EXISTS users"));
        assert!(result.sql_ddl.contains("CREATE TABLE IF NOT EXISTS orders"));
    }

    #[test]
    fn test_singularisation() {
        assert_eq!(to_singular("users"), "user");
        assert_eq!(to_singular("orders"), "order");
        assert_eq!(to_singular("categories"), "category");
        assert_eq!(to_singular("status"), "status");
    }

    #[test]
    fn test_pascal_case() {
        assert_eq!(to_pascal_case("user"), "User");
        assert_eq!(to_pascal_case("order_item"), "OrderItem");
    }
}
