// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateLlmAgentSessionRequest { provider: string, model: string, system_prompt: string | null, }