// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateTerminalSessionRequest { project_id?: string, tool_name: string, prompt?: string, interactive: boolean, requires_pty: boolean, env?: Record<string, string>, cols?: number, rows?: number, }