// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileInfo } from "./FileInfo";

export interface FileListResponse { files: Array<FileInfo>, current_path: string, total_files: number, truncated: boolean, limit: number, }