// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LlmAgentMessage { id: number, session_id: number, role: string, content: string, created_at: number, }