// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";
import type { ProjectComponent } from "./ProjectComponent";

export interface ProjectDetailsResponse { project: Project, components: Array<ProjectComponent>, }