// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TerminalSession { id: string, work_id: string, message_id: string, tool_name: string, status: string, project_context: string | null, requires_pty: boolean, interactive: boolean, cols: number, rows: number, started_at: number, ended_at: number | null, exit_code?: number, }