---
- name: Check Nocodo Services API Status
  hosts: nocodo_servers
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Check service status
      command: systemctl is-active nocodo-services.service
      register: service_status
      changed_when: false

    - name: Display service status
      debug:
        msg: "Service is {{ 'running' if service_status.stdout == 'active' else 'not running' }}"

    - name: Check Nginx configuration
      command: nginx -t
      register: nginx_check
      changed_when: false
      ignore_errors: yes

    - name: Display Nginx status
      debug:
        msg: "Nginx configuration is {{ 'valid' if nginx_check.rc == 0 else 'invalid' }}"

    - name: Check SSL certificate
      stat:
        path: /etc/letsencrypt/live/{{ nocodo_domain }}/fullchain.pem
      register: ssl_cert
      changed_when: false

    - name: Display SSL status
      debug:
        msg: "SSL certificate {{ 'found' if ssl_cert.stat.exists else 'not found' }}"